In [2]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
import seaborn as sns

In [4]:
df = pd.read_csv("D:/Coding/Python/amazon_products_sales_data_uncleaned.csv")
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,NaN,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,https://m.media-amazon.com/images/I/51KCB+egEs...,/Elgato-4K-Pro-Internal-Capture/dp/B0DLR3WQWR/...,2025-08-30 19:56:33
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,https://m.media-amazon.com/images/I/51jV+o1LZE...,/Arlo-Essential-Spotlight-Camera-Surveillance/...,2025-08-30 19:56:33
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71ySPkNLkG...,/GIGABYTE-FO32U2-32-3840x2160-240Hz-FreeSync-A...,2025-08-30 19:56:33
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,https://m.media-amazon.com/images/I/411c0JFJ79...,/Monoprice-XLR-Male-4-Inch-Cable/dp/B001UJEKZ6...,2025-08-30 19:56:33
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71wTn+zoSr...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,2025-08-30 19:56:33

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  object
 2   number_of_reviews         41651 non-null  object
 3   bought_in_last_month      39458 non-null  object
 4   current/discounted_price  30926 non-null  object
 5   price_on_variant          42675 non-null  object
 6   listed_price              42675 non-null  object
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  buy_box_availability      28022 non-null  object
 11  delivery_details          30955 non-null  object
 12  sustainability_badges     3408 non-null   object
 13  image_url                 42675 non-null  object
 14  product_url               40606 non-null  object
 15  collected_at              42675 non-null  object
dtypes: object(16)
memory usage: 5.2+ MB

In [6]:
df.drop(columns=["image_url"],inplace=True) 
df.drop(columns=["product_url"],inplace=True)

In [7]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,2025-08-21 11:14:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,NaN,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,2025-08-30 19:56:33
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,2025-08-30 19:56:33
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,2025-08-30 19:56:33
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33

In [8]:
df['buy_box_availability'].unique()

array(['Add to cart', nan], dtype=object)

In [9]:
df = pd.get_dummies(df , columns=['buy_box_availability'], drop_first= True)

In [10]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,delivery_details,sustainability_badges,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,"Delivery Mon, Sep 1",Carbon impact,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,"Delivery Fri, Aug 29",NaN,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,"Delivery Mon, Sep 1",NaN,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,2025-08-21 11:14:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,2025-08-30 19:56:33
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,2025-08-30 19:56:33
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,2025-08-30 19:56:33
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33

In [11]:
df['current/discounted_price'] = df['current/discounted_price'].fillna(0)

In [12]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,delivery_details,sustainability_badges,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,"Delivery Mon, Sep 1",Carbon impact,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,"Delivery Fri, Aug 29",NaN,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,"Delivery Mon, Sep 1",NaN,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,0,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,0,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,2025-08-21 11:14:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,2025-08-30 19:56:33
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,2025-08-30 19:56:33
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,2025-08-30 19:56:33
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  object
 2   number_of_reviews         41651 non-null  object
 3   bought_in_last_month      39458 non-null  object
 4   current/discounted_price  42675 non-null  object
 5   price_on_variant          42675 non-null  object
 6   listed_price              42675 non-null  object
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  delivery_details          30955 non-null  object
 11  sustainability_badges     3408 non-null   object
 12  collected_at              42675 non-null  object
dtypes: object(13)
memory usage: 4.2+ MB

In [14]:
df['rating'].unique

<bound method Series.unique of 0        4.6 out of 5 stars
1        4.3 out of 5 stars
2        4.6 out of 5 stars
3        4.6 out of 5 stars
4        4.8 out of 5 stars
                ...
42670    5.0 out of 5 stars
42671    4.2 out of 5 stars
42672    4.3 out of 5 stars
42673    4.7 out of 5 stars
42674    4.4 out of 5 stars
Name: rating, Length: 42675, dtype: object>

In [15]:
df['rating'] = df['rating'].str.extract(r'(\d+\.?\d*)').astype(float)

In [16]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,delivery_details,sustainability_badges,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,"Delivery Mon, Sep 1",Carbon impact,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,"Delivery Fri, Aug 29",NaN,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,"3,044",2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,"Delivery Mon, Sep 1",NaN,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,"35,882",10K+ bought in past month,0,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,"28,988",10K+ bought in past month,0,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,2025-08-21 11:14:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,2025-08-30 19:56:33
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,2025-08-30 19:56:33
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,2025-08-30 19:56:33
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33

In [17]:
df['title'].unique()

array(['BOYA BOYALINK 2 Wireless Lavalier Microphone for iPhone Camera Android, Mini Lapel Micophone Wireless, 48 KHz 24 Bit, 6mm Mic, 1000ft, 30h Use, Noise Cancelling, Clip on Mic USB-C/Lightning/3.5mm TRS',
       'LISEN USB C to Lightning Cable, 240W 4 in 1 Charging Cable 6.6FT, Chubby USB A/C to C/Lightning with Light for iPhone 16e 15 14 Pro/MacBook Air 17/iPad/Samsung/Switch 2, Multi Chargers for All Devices',
       'DJI Mic 2 (2 TX + 1 RX + Charging Case), Wireless Lavalier Microphone, Intelligent Noise Cancelling, 32-bit Float Internal Recording, 820 ft.(250m) Range, Microphone for iPhone, Android, Camera',
       ...,
       'Monster Clarity 8.0 Hybrid Active Noise Cancelling Wireless Earbuds, 42dB in-Ear ANC Earphones Deep Bass with 6 Mics, Bluetooth 5.2, 50H Play Time with Wireless Charging Case,Blue',
       'Audio-Technica HP-EP Replacement Ear Pads for M Series Headphones',
       'Apple 2022 MacBook Air Laptop with M2 chip (13.6-inch, 8GB RAM, 256GB SSD Storage) Starlight (Renewed)'],
      shape=(8808,), dtype=object)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  float64
 2   number_of_reviews         41651 non-null  object
 3   bought_in_last_month      39458 non-null  object
 4   current/discounted_price  42675 non-null  object
 5   price_on_variant          42675 non-null  object
 6   listed_price              42675 non-null  object
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  delivery_details          30955 non-null  object
 11  sustainability_badges     3408 non-null   object
 12  collected_at              42675 non-null  object
dtypes: float64(1), object(12)
memory usage: 4.2+ MB

In [19]:
df['number_of_reviews'] = df['number_of_reviews'].str.replace(',', '').fillna('0').astype(int)

In [20]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,delivery_details,sustainability_badges,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,"Delivery Mon, Sep 1",Carbon impact,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457,6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,"Delivery Fri, Aug 29",NaN,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044,2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,"Delivery Mon, Sep 1",NaN,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882,10K+ bought in past month,0,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988,10K+ bought in past month,0,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,2025-08-21 11:14:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,2025-08-30 19:56:33
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,2025-08-30 19:56:33
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,7102,500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,2025-08-30 19:56:33
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  float64
 2   number_of_reviews         42675 non-null  int64
 3   bought_in_last_month      39458 non-null  object
 4   current/discounted_price  42675 non-null  object
 5   price_on_variant          42675 non-null  object
 6   listed_price              42675 non-null  object
 7   is_best_seller            42675 non-null  object
 8   is_sponsored              42675 non-null  object
 9   is_couponed               42675 non-null  object
 10  delivery_details          30955 non-null  object
 11  sustainability_badges     3408 non-null   object
 12  collected_at              42675 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 4.2+ MB

In [22]:
df = pd.get_dummies(df , columns=['is_sponsored'], drop_first= True)

In [23]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_couponed,delivery_details,sustainability_badges,collected_at,is_sponsored_Sponsored
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Save 15% with coupon,"Delivery Mon, Sep 1",Carbon impact,2025-08-21 11:14:29,True
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457,6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,No Coupon,"Delivery Fri, Aug 29",NaN,2025-08-21 11:14:29,True
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044,2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,No Coupon,"Delivery Mon, Sep 1",NaN,2025-08-21 11:14:29,True
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882,10K+ bought in past month,0,basic variant price: $162.24,No Discount,Best Seller,No Coupon,NaN,NaN,2025-08-21 11:14:29,False
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988,10K+ bought in past month,0,basic variant price: $72.74,No Discount,No Badge,No Coupon,NaN,NaN,2025-08-21 11:14:29,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,2025-08-30 19:56:33,False
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Save $25.00 with coupon,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,2025-08-30 19:56:33,False
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33,False
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,7102,500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,No Coupon,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,2025-08-30 19:56:33,False
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33,False

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  float64
 2   number_of_reviews         42675 non-null  int64
 3   bought_in_last_month      39458 non-null  object
 4   current/discounted_price  42675 non-null  object
 5   price_on_variant          42675 non-null  object
 6   listed_price              42675 non-null  object
 7   is_best_seller            42675 non-null  object
 8   is_couponed               42675 non-null  object
 9   delivery_details          30955 non-null  object
 10  sustainability_badges     3408 non-null   object
 11  collected_at              42675 non-null  object
 12  is_sponsored_Sponsored    42675 non-null  bool
dtypes: bool(1), float64(1), int64(1), object(10)
memory usage: 3.9+ MB

In [25]:
df['current/discounted_price'].unique()

array(['89.68', '9.99', '314.00', ..., '1,579.99', '20.14', '1,252.29'],
      shape=(2577,), dtype=object)

In [26]:
df.drop(columns=["price_on_variant"],inplace=True)

In [27]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,listed_price,is_best_seller,is_couponed,delivery_details,sustainability_badges,collected_at,is_sponsored_Sponsored
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375,300+ bought in past month,89.68,$159.00,No Badge,Save 15% with coupon,"Delivery Mon, Sep 1",Carbon impact,2025-08-21 11:14:29,True
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457,6K+ bought in past month,9.99,$15.99,No Badge,No Coupon,"Delivery Fri, Aug 29",NaN,2025-08-21 11:14:29,True
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044,2K+ bought in past month,314.00,$349.00,No Badge,No Coupon,"Delivery Mon, Sep 1",NaN,2025-08-21 11:14:29,True
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882,10K+ bought in past month,0,No Discount,Best Seller,No Coupon,NaN,NaN,2025-08-21 11:14:29,False
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988,10K+ bought in past month,0,No Discount,No Badge,No Coupon,NaN,NaN,2025-08-21 11:14:29,False
...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1,100+ bought in past month,195.99,No Discount,No Badge,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,2025-08-30 19:56:33,False
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20,200+ bought in past month,89.99,No Discount,No Badge,Save $25.00 with coupon,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,2025-08-30 19:56:33,False
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57,50+ bought in past month,899.99,"$1,099.99",Save 18%,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33,False
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,7102,500+ bought in past month,10.39,$15.98,No Badge,No Coupon,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,2025-08-30 19:56:33,False
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75,50+ bought in past month,419.99,$499.99,No Badge,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33,False

In [28]:
df['bought_in_last_month'] = df['bought_in_last_month'].str.extract(r'(\d+\.?\d*)').astype(float)

In [29]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,listed_price,is_best_seller,is_couponed,delivery_details,sustainability_badges,collected_at,is_sponsored_Sponsored
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375,300.0,89.68,$159.00,No Badge,Save 15% with coupon,"Delivery Mon, Sep 1",Carbon impact,2025-08-21 11:14:29,True
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457,6.0,9.99,$15.99,No Badge,No Coupon,"Delivery Fri, Aug 29",NaN,2025-08-21 11:14:29,True
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044,2.0,314.00,$349.00,No Badge,No Coupon,"Delivery Mon, Sep 1",NaN,2025-08-21 11:14:29,True
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882,10.0,0,No Discount,Best Seller,No Coupon,NaN,NaN,2025-08-21 11:14:29,False
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988,10.0,0,No Discount,No Badge,No Coupon,NaN,NaN,2025-08-21 11:14:29,False
...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1,100.0,195.99,No Discount,No Badge,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,2025-08-30 19:56:33,False
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20,200.0,89.99,No Discount,No Badge,Save $25.00 with coupon,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,2025-08-30 19:56:33,False
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57,50.0,899.99,"$1,099.99",Save 18%,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33,False
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,7102,500.0,10.39,$15.98,No Badge,No Coupon,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,2025-08-30 19:56:33,False
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75,50.0,419.99,$499.99,No Badge,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33,False

In [30]:
df['listed_price'] = pd.to_numeric(
    df['listed_price'].str.replace('$', '', regex=False)
                       .str.replace(',', '', regex=False)
                       .replace('No Discount', '0'),
    errors='coerce'
).fillna(0).astype(float)

In [31]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,listed_price,is_best_seller,is_couponed,delivery_details,sustainability_badges,collected_at,is_sponsored_Sponsored
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375,300.0,89.68,159.00,No Badge,Save 15% with coupon,"Delivery Mon, Sep 1",Carbon impact,2025-08-21 11:14:29,True
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457,6.0,9.99,15.99,No Badge,No Coupon,"Delivery Fri, Aug 29",NaN,2025-08-21 11:14:29,True
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044,2.0,314.00,349.00,No Badge,No Coupon,"Delivery Mon, Sep 1",NaN,2025-08-21 11:14:29,True
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882,10.0,0,0.00,Best Seller,No Coupon,NaN,NaN,2025-08-21 11:14:29,False
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988,10.0,0,0.00,No Badge,No Coupon,NaN,NaN,2025-08-21 11:14:29,False
...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1,100.0,195.99,0.00,No Badge,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,2025-08-30 19:56:33,False
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20,200.0,89.99,0.00,No Badge,Save $25.00 with coupon,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,2025-08-30 19:56:33,False
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57,50.0,899.99,1099.99,Save 18%,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33,False
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,7102,500.0,10.39,15.98,No Badge,No Coupon,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,2025-08-30 19:56:33,False
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75,50.0,419.99,499.99,No Badge,No Coupon,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33,False

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  float64
 2   number_of_reviews         42675 non-null  int64
 3   bought_in_last_month      32233 non-null  float64
 4   current/discounted_price  42675 non-null  object
 5   listed_price              42675 non-null  float64
 6   is_best_seller            42675 non-null  object
 7   is_couponed               42675 non-null  object
 8   delivery_details          30955 non-null  object
 9   sustainability_badges     3408 non-null   object
 10  collected_at              42675 non-null  object
 11  is_sponsored_Sponsored    42675 non-null  bool
dtypes: bool(1), float64(3), int64(1), object(7)
memory usage: 3.6+ MB

In [33]:
labelencoder = LabelEncoder()
encodeddata = labelencoder.fit_transform(df['is_couponed'])
df['is_couponed'] = encodeddata
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,listed_price,is_best_seller,is_couponed,delivery_details,sustainability_badges,collected_at,is_sponsored_Sponsored
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375,300.0,89.68,159.00,No Badge,31,"Delivery Mon, Sep 1",Carbon impact,2025-08-21 11:14:29,True
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457,6.0,9.99,15.99,No Badge,0,"Delivery Fri, Aug 29",NaN,2025-08-21 11:14:29,True
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044,2.0,314.00,349.00,No Badge,0,"Delivery Mon, Sep 1",NaN,2025-08-21 11:14:29,True
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882,10.0,0,0.00,Best Seller,0,NaN,NaN,2025-08-21 11:14:29,False
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988,10.0,0,0.00,No Badge,0,NaN,NaN,2025-08-21 11:14:29,False
...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1,100.0,195.99,0.00,No Badge,0,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,2025-08-30 19:56:33,False
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20,200.0,89.99,0.00,No Badge,16,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,2025-08-30 19:56:33,False
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57,50.0,899.99,1099.99,Save 18%,0,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33,False
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,7102,500.0,10.39,15.98,No Badge,0,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,2025-08-30 19:56:33,False
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75,50.0,419.99,499.99,No Badge,0,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33,False

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  float64
 2   number_of_reviews         42675 non-null  int64
 3   bought_in_last_month      32233 non-null  float64
 4   current/discounted_price  42675 non-null  object
 5   listed_price              42675 non-null  float64
 6   is_best_seller            42675 non-null  object
 7   is_couponed               42675 non-null  int64
 8   delivery_details          30955 non-null  object
 9   sustainability_badges     3408 non-null   object
 10  collected_at              42675 non-null  object
 11  is_sponsored_Sponsored    42675 non-null  bool
dtypes: bool(1), float64(3), int64(2), object(6)
memory usage: 3.6+ MB

In [35]:
df.columns

Index(['title', 'rating', 'number_of_reviews', 'bought_in_last_month',
       'current/discounted_price', 'listed_price', 'is_best_seller',
       'is_couponed', 'delivery_details', 'sustainability_badges',
       'collected_at', 'is_sponsored_Sponsored'],
      dtype='object')

In [36]:
df['current/discounted_price'].unique()

array(['89.68', '9.99', '314.00', ..., '1,579.99', '20.14', '1,252.29'],
      shape=(2577,), dtype=object)

In [37]:
df['current/discounted_price'] = df['current/discounted_price'].str.replace(',', '').fillna('0').astype(float)

In [38]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,listed_price,is_best_seller,is_couponed,delivery_details,sustainability_badges,collected_at,is_sponsored_Sponsored
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375,300.0,89.68,159.00,No Badge,31,"Delivery Mon, Sep 1",Carbon impact,2025-08-21 11:14:29,True
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457,6.0,9.99,15.99,No Badge,0,"Delivery Fri, Aug 29",NaN,2025-08-21 11:14:29,True
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044,2.0,314.00,349.00,No Badge,0,"Delivery Mon, Sep 1",NaN,2025-08-21 11:14:29,True
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882,10.0,0.00,0.00,Best Seller,0,NaN,NaN,2025-08-21 11:14:29,False
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988,10.0,0.00,0.00,No Badge,0,NaN,NaN,2025-08-21 11:14:29,False
...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1,100.0,195.99,0.00,No Badge,0,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,2025-08-30 19:56:33,False
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20,200.0,89.99,0.00,No Badge,16,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,2025-08-30 19:56:33,False
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57,50.0,899.99,1099.99,Save 18%,0,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33,False
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,7102,500.0,10.39,15.98,No Badge,0,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,2025-08-30 19:56:33,False
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75,50.0,419.99,499.99,No Badge,0,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,2025-08-30 19:56:33,False

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  float64
 2   number_of_reviews         42675 non-null  int64
 3   bought_in_last_month      32233 non-null  float64
 4   current/discounted_price  42675 non-null  float64
 5   listed_price              42675 non-null  float64
 6   is_best_seller            42675 non-null  object
 7   is_couponed               42675 non-null  int64
 8   delivery_details          30955 non-null  object
 9   sustainability_badges     3408 non-null   object
 10  collected_at              42675 non-null  object
 11  is_sponsored_Sponsored    42675 non-null  bool
dtypes: bool(1), float64(4), int64(2), object(5)
memory usage: 3.6+ MB

In [40]:
df.drop(columns=["delivery_details"],inplace=True)

In [41]:
df['collected_at'].unique()

array(['2025-08-21 11:14:29', '2025-08-21 11:14:46',
       '2025-08-21 11:14:47', ..., '2025-08-30 19:55:04',
       '2025-08-30 19:55:28', '2025-08-30 19:56:33'],
      shape=(1559,), dtype=object)

In [42]:
df.drop(columns=["collected_at"],inplace=True)

In [43]:
labelencoder = LabelEncoder()
encodeddata = labelencoder.fit_transform(df['sustainability_badges'])
df['sustainability_badges'] = encodeddata
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,listed_price,is_best_seller,is_couponed,sustainability_badges,is_sponsored_Sponsored
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375,300.0,89.68,159.00,No Badge,31,2,True
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457,6.0,9.99,15.99,No Badge,0,16,True
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044,2.0,314.00,349.00,No Badge,0,16,True
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882,10.0,0.00,0.00,Best Seller,0,16,False
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988,10.0,0.00,0.00,No Badge,0,16,False
...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1,100.0,195.99,0.00,No Badge,0,16,False
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20,200.0,89.99,0.00,No Badge,16,16,False
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57,50.0,899.99,1099.99,Save 18%,0,16,False
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,7102,500.0,10.39,15.98,No Badge,0,16,False
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75,50.0,419.99,499.99,No Badge,0,16,False

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  object
 1   rating                    41651 non-null  float64
 2   number_of_reviews         42675 non-null  int64
 3   bought_in_last_month      32233 non-null  float64
 4   current/discounted_price  42675 non-null  float64
 5   listed_price              42675 non-null  float64
 6   is_best_seller            42675 non-null  object
 7   is_couponed               42675 non-null  int64
 8   sustainability_badges     42675 non-null  int64
 9   is_sponsored_Sponsored    42675 non-null  bool
dtypes: bool(1), float64(4), int64(3), object(2)
memory usage: 3.0+ MB

In [45]:
df['title'].unique()

array(['BOYA BOYALINK 2 Wireless Lavalier Microphone for iPhone Camera Android, Mini Lapel Micophone Wireless, 48 KHz 24 Bit, 6mm Mic, 1000ft, 30h Use, Noise Cancelling, Clip on Mic USB-C/Lightning/3.5mm TRS',
       'LISEN USB C to Lightning Cable, 240W 4 in 1 Charging Cable 6.6FT, Chubby USB A/C to C/Lightning with Light for iPhone 16e 15 14 Pro/MacBook Air 17/iPad/Samsung/Switch 2, Multi Chargers for All Devices',
       'DJI Mic 2 (2 TX + 1 RX + Charging Case), Wireless Lavalier Microphone, Intelligent Noise Cancelling, 32-bit Float Internal Recording, 820 ft.(250m) Range, Microphone for iPhone, Android, Camera',
       ...,
       'Monster Clarity 8.0 Hybrid Active Noise Cancelling Wireless Earbuds, 42dB in-Ear ANC Earphones Deep Bass with 6 Mics, Bluetooth 5.2, 50H Play Time with Wireless Charging Case,Blue',
       'Audio-Technica HP-EP Replacement Ear Pads for M Series Headphones',
       'Apple 2022 MacBook Air Laptop with M2 chip (13.6-inch, 8GB RAM, 256GB SSD Storage) Starlight (Renewed)'],
      shape=(8808,), dtype=object)

In [46]:
df["is_best_seller"] = df["is_best_seller"].apply(lambda x: 1 if x == "Best Seller" else 0)

In [47]:
df.drop(columns=["title"],inplace=True)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   rating                    41651 non-null  float64
 1   number_of_reviews         42675 non-null  int64
 2   bought_in_last_month      32233 non-null  float64
 3   current/discounted_price  42675 non-null  float64
 4   listed_price              42675 non-null  float64
 5   is_best_seller            42675 non-null  int64
 6   is_couponed               42675 non-null  int64
 7   sustainability_badges     42675 non-null  int64
 8   is_sponsored_Sponsored    42675 non-null  bool
dtypes: bool(1), float64(4), int64(4)
memory usage: 2.6 MB

In [49]:
df.isna().sum()

rating                       1024
number_of_reviews               0
bought_in_last_month        10442
current/discounted_price        0
listed_price                    0
is_best_seller                  0
is_couponed                     0
sustainability_badges           0
is_sponsored_Sponsored          0
dtype: int64

In [50]:
df_noNulls=df.dropna(axis=0)

In [51]:
df_noNulls.isna().sum()

rating                      0
number_of_reviews           0
bought_in_last_month        0
current/discounted_price    0
listed_price                0
is_best_seller              0
is_couponed                 0
sustainability_badges       0
is_sponsored_Sponsored      0
dtype: int64

In [52]:
df['rating'].fillna(df['rating'].mode()[0] , inplace=True)
df['bought_in_last_month'].fillna(df['bought_in_last_month'].mode()[0] , inplace=True)

C:\Users\me067\AppData\Local\Temp\ipykernel_21268\3145602379.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['rating'].fillna(df['rating'].mode()[0] , inplace=True)
C:\Users\me067\AppData\Local\Temp\ipykernel_21268\3145602379.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bought_in_last_month'].fillna(df['bought_in_last_month'].mode()[0] , inplace=True)

In [53]:
df.isna().sum()

rating                      0
number_of_reviews           0
bought_in_last_month        0
current/discounted_price    0
listed_price                0
is_best_seller              0
is_couponed                 0
sustainability_badges       0
is_sponsored_Sponsored      0
dtype: int64

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   rating                    42675 non-null  float64
 1   number_of_reviews         42675 non-null  int64
 2   bought_in_last_month      42675 non-null  float64
 3   current/discounted_price  42675 non-null  float64
 4   listed_price              42675 non-null  float64
 5   is_best_seller            42675 non-null  int64
 6   is_couponed               42675 non-null  int64
 7   sustainability_badges     42675 non-null  int64
 8   is_sponsored_Sponsored    42675 non-null  bool
dtypes: bool(1), float64(4), int64(4)
memory usage: 2.6 MB

In [55]:
train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["is_best_seller"])
train, val = train_test_split(train, test_size=0.2, random_state=42, stratify=train["is_best_seller"])
x_train = train[["listed_price"]]
x_val = val[["listed_price"]]
x_test = test[["listed_price"]]
y_train = train["is_best_seller"]
y_val = val["is_best_seller"]
y_test = test["is_best_seller"]

In [56]:
standard_scaler = StandardScaler()
x_test=standard_scaler.fit_transform(x_test)
x_train=standard_scaler.fit_transform(x_train)

In [57]:
lr = LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [58]:
knn = KNeighborsClassifier()
knn.fit(x_train , y_train)

KNeighborsClassifier()

In [59]:
lr.score(x_test, y_test)

0.9935559461042766

In [60]:
knn.score(x_test, y_test)

0.9925014645577036

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   rating                    42675 non-null  float64
 1   number_of_reviews         42675 non-null  int64
 2   bought_in_last_month      42675 non-null  float64
 3   current/discounted_price  42675 non-null  float64
 4   listed_price              42675 non-null  float64
 5   is_best_seller            42675 non-null  int64
 6   is_couponed               42675 non-null  int64
 7   sustainability_badges     42675 non-null  int64
 8   is_sponsored_Sponsored    42675 non-null  bool
dtypes: bool(1), float64(4), int64(4)
memory usage: 2.6 MB